db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: 111111
    MYSQL_DATABASE: distance_learning
    MYSQL_USER: root
    MYSQL_PASSWORD: 112233

web:
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/srv/www
  links:
    - db